name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build for Windows and Linux on both x86_64 and ARM64
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "locc"
        extra_files: LICENSE README.md
        md5sum: false
        sha256sum: true
